[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-s"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-s"]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
